version: "3.9"

services:
  ros1_ci:
    build: .
    container_name: ros1_ci_container
    image: ros1_ci:latest
    environment:
      - DISPLAY=${DISPLAY}
      - QT_X11_NO_MITSHM=1
      - TURTLEBOT3_MODEL=burger
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - ./tortoisebot_simulation:/root/simulation_ws/src/ros1_ci/tortoisebot_simulation
      - ./tortoisebot_waypoints:/root/simulation_ws/src/ros1_ci/tortoisebot_waypoints
    network_mode: bridge
    stdin_open: true
    tty: true
