version: "3.9"

x-common-env: &common_env
  PYTHONUNBUFFERED: "1"
  LIBGL_ALWAYS_SOFTWARE: "1"
  ROS_MASTER_URI: "http://ros1_ci:11311"

services:
  ros1_ci:
    build: .
    image: ros1_ci:latest
    container_name: ros1_ci
    environment:
      <<: *common_env
      DISPLAY: "${DISPLAY:-}"
      QT_X11_NO_MITSHM: "1"
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
    command: >
      bash -lc "
        source /opt/ros/noetic/setup.bash &&
        source ~/simulation_ws/devel/setup.bash &&
        catkin_make &&
        source ~/simulation_ws/devel/setup.bash &&
        roslaunch tortoisebot_gazebo tortoisebot_playground.launch gui:=false
      "

  waypoints_action:
    image: ros1_ci:latest
    depends_on:
      - ros1_ci
    environment: *common_env
    command: >
      bash -lc "
        source /opt/ros/noetic/setup.bash &&
        catkin_make
        source ~/simulation_ws/devel/setup.bash &&
        sleep 10 &&
        rosrun tortoisebot_waypoints tortoisebot_action_server.py
      "

  ros_tests:
    image: ros1_ci:latest
    depends_on:
      - ros1_ci
      - waypoints_action
    environment: *common_env
    command: >
      bash -lc "
        source /opt/ros/noetic/setup.bash &&
        source ~/simulation_ws/devel/setup.bash &&
        sleep 45 &&
        rostest tortoisebot_waypoints waypoints_test.test --reuse-master
      "
